### ISSUE TITLE
space

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Jomhuria#10]
I believe space it has to be tighter

**Comment by graphicore** [comment]
@EbenSorkin wrote:

> Still, I’ll need the space so I added it and made it match the 600 units you have. This seems wide for the latin in a display font for sure. Would you guys look and see if this needs to be this wide for the Arabic? To my eye it looks a bit wide there too.

So you all agree. What's the number then?

**Comment by graphicore** [comment]
@Tarobish @EbenSorkin space is now 450. Please check if that's good.

**Comment by EbenSorkin** [comment]
I checked and 400 seems like better than 450 but the Arabic should be the deciding factor.

Kourosh?

Sample image

-e.

**Comment by EbenSorkin** [comment]
I checked too
I do agree with Eben, it could be 400

**Comment by graphicore** [comment]
@Tarobish @EbenSorkin space is now 400. Please check.

**Comment by Tarobish** [comment]
I’m happy :) Many Thanks
