### ISSUE TITLE
Colliding glyph combinations above the baseline

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Jomhuria#11]
here is the glyph's name, which has colliding above the baseline
like تا ثا تآ ثآ ثلا تلا ثلآ ثاٍ تاِ
probably we can use "aAlf.fina.alt" as a replacement for the whole colliding with "Alef" with and without marks except "uni0622.fina" uniFE82 (letter Alef with Maddah above)

uni0753.init
uni0751.init
uni067D.init
uni067F.init
uni067C.init
uni062B.init
uni062A.init
uniFB64
uniFE97
uniFE9B
u1EE35
u1EE36

In Connection With 

aAlf.fina
uni0625.fina
uni0627.fina
uni0774.fina
uni0773.fina
uni0623.fina
uni0622.fina
uni0675.fina
uni0672.fina
uni0673.fina
uni0671.fina
uniFB51
uniFE82
uniFE84
uniFE88
uniFE8E
u1EE6F
aLam.medi_LamAlfFina
aAlf.fina
uni076A.medi_LamAlfFina
uni06B6.medi_LamAlfFina
uni06B8.medi_LamAlfFina
uni0644.medi_LamAlfFina
uni06B7.medi_LamAlfFina
uni06B5.medi_LamAlfFina
uniFEFC
uniFEFA
uniFEF8
uniFEF6

**Comment by Tarobish** [comment]
please check these (all the character in combination with uni0625.fina)
uni0680.init(first) + uni0625.fina(second)	‌ڀإ‌	‌ڀ‍ + ‍إ‌
uni0776.init(first) + uni0625.fina(second)	‌ݶإ‌	‌ݶ‍ + ‍إ‌
uni06CE.init(first) + uni0625.fina(second)	‌ێإ‌	‌ێ‍ + ‍إ‌
uni0775.init(first) + uni0625.fina(second)	‌ݵإ‌	‌ݵ‍ + ‍إ‌
uni06BD.init(first) + uni0625.fina(second)	‌ڽإ‌	‌ڽ‍ + ‍إ‌
uni064A.init(first) + uni0625.fina(second)	‌يإ‌	‌ي‍ + ‍إ‌
uni067E.init(first) + uni0625.fina(second)	‌پإ‌	‌پ‍ + ‍إ‌
uni0753.init(first) + uni0625.fina(second)	‌ݓإ‌	‌ݓ‍ + ‍إ‌
uni0752.init(first) + uni0625.fina(second)	‌ݒإ‌	‌ݒ‍ + ‍إ‌
uni063D.init(first) + uni0625.fina(second)	‌ؽإ‌	‌ؽ‍ + ‍إ‌
uni0754.init(first) + uni0625.fina(second)	‌ݔإ‌	‌ݔ‍ + ‍إ‌
uni06D1.init(first) + uni0625.fina(second)	‌ۑإ‌	‌ۑ‍ + ‍إ‌
uni06CC.init(first) + uni0625.fina(second)	‌یإ‌	‌ی‍ + ‍إ‌
uni0767.init(first) + uni0625.fina(second)	‌ݧإ‌	‌ݧ‍ + ‍إ‌
uni0680.medi(first) + uni0625.fina(second)	‌‍ڀإ‌	‌‍ڀ‍ + ‍إ‌
uni0776.medi(first) + uni0625.fina(second)	‌‍ݶإ‌	‌‍ݶ‍ + ‍إ‌
uni06CE.medi(first) + uni0625.fina(second)	‌‍ێإ‌	‌‍ێ‍ + ‍إ‌
uni0775.medi(first) + uni0625.fina(second)	‌‍ݵإ‌	‌‍ݵ‍ + ‍إ‌
uni06BD.medi(first) + uni0625.fina(second)	‌‍ڽإ‌	‌‍ڽ‍ + ‍إ‌
uni064A.medi(first) + uni0625.fina(second)	‌‍يإ‌	‌‍ي‍ + ‍إ‌
uni067E.medi(first) + uni0625.fina(second)	‌‍پإ‌	‌‍پ‍ + ‍إ‌
uni0753.medi(first) + uni0625.fina(second)	‌‍ݓإ‌	‌‍ݓ‍ + ‍إ‌
uni0752.medi(first) + uni0625.fina(second)	‌‍ݒإ‌	‌‍ݒ‍ + ‍إ‌
uni063D.medi(first) + uni0625.fina(second)	‌‍ؽإ‌	‌‍ؽ‍ + ‍إ‌
uni0754.medi(first) + uni0625.fina(second)	‌‍ݔإ‌	‌‍ݔ‍ + ‍إ‌
uni06D1.medi(first) + uni0625.fina(second)	‌‍ۑإ‌	‌‍ۑ‍ + ‍إ‌
uni06CC.medi(first) + uni0625.fina(second)	‌‍یإ‌	‌‍ی‍ + ‍إ‌
uni0767.medi(first) + uni0625.fina(second)	‌‍ݧإ‌	‌‍ݧ‍ + ‍إ‌

**Comment by Tarobish** [comment]
also these characters
(uniFEF3)
uniFEF3(first) + uniFBA9(second)	‌ﻳﮩ‌	‌ﻳ‍ + ‍ﮩ‌
uniFEF3(first) + uniFBAF(second)	‌ﻳﮯ‌	‌ﻳ‍ + ‍ﮯ‌
uniFEF3(first) + uniFBE5(second)	‌ﻳﯥ‌	‌ﻳ‍ + ‍ﯥ‌
uniFEF3(first) + uniFBFD(second)	‌ﻳﯽ‌	‌ﻳ‍ + ‍ﯽ‌
uniFEF3(first) + uniFC10(second)	‌ﻳﰐ‌	‌ﻳ‍ + ‍ﰐ‌
uniFEF3(first) + uniFC90(second)	‌ﻳﲐ‌	‌ﻳ‍ + ‍ﲐ‌
uniFEF3(first) + uniFD17(second)	‌ﻳﴗ‌	‌ﻳ‍ + ‍ﴗ‌
uniFEF3(first) + uniFD18(second)	‌ﻳﴘ‌	‌ﻳ‍ + ‍ﴘ‌
uniFEF3(first) + uniFE8A(second)	‌ﻳﺊ‌	‌ﻳ‍ + ‍ﺊ‌
uniFEF3(first) + uniFEF0(second)	‌ﻳﻰ‌	‌ﻳ‍ + ‍ﻰ‌
uniFEF3(first) + uniFEF2(second)	‌ﻳﻲ‌	‌ﻳ‍ + ‍ﻲ‌

(uniFB58)
uniFB58(first) + uniFBAF(second)	‌ﭘﮯ‌	‌ﭘ‍ + ‍ﮯ‌
uniFB58(first) + uniFBE5(second)	‌ﭘﯥ‌	‌ﭘ‍ + ‍ﯥ‌
uniFB58(first) + uniFBFD(second)	‌ﭘﯽ‌	‌ﭘ‍ + ‍ﯽ‌
uniFB58(first) + uniFC10(second)	‌ﭘﰐ‌	‌ﭘ‍ + ‍ﰐ‌
uniFB58(first) + uniFC90(second)	‌ﭘﲐ‌	‌ﭘ‍ + ‍ﲐ‌
uniFB58(first) + uniFD17(second)	‌ﭘﴗ‌	‌ﭘ‍ + ‍ﴗ‌
uniFB58(first) + uniFD18(second)	‌ﭘﴘ‌	‌ﭘ‍ + ‍ﴘ‌
uniFB58(first) + uniFE8A(second)	‌ﭘﺊ‌	‌ﭘ‍ + ‍ﺊ‌
uniFB58(first) + uniFEF0(second)	‌ﭘﻰ‌	‌ﭘ‍ + ‍ﻰ‌
uniFB58(first) + uniFEF2(second)	‌ﭘﻲ‌	‌ﭘ‍ + ‍ﻲ‌

(uniFB5C)
uniFB5C(first) + uniFBA9(second)	‌ﭜﮩ‌	‌ﭜ‍ + ‍ﮩ‌
uniFB5C(first) + uniFBAF(second)	‌ﭜﮯ‌	‌ﭜ‍ + ‍ﮯ‌
uniFB5C(first) + uniFBE5(second)	‌ﭜﯥ‌	‌ﭜ‍ + ‍ﯥ‌
uniFB5C(first) + uniFBFD(second)	‌ﭜﯽ‌	‌ﭜ‍ + ‍ﯽ‌
uniFB5C(first) + uniFC10(second)	‌ﭜﰐ‌	‌ﭜ‍ + ‍ﰐ‌
uniFB5C(first) + uniFC90(second)	‌ﭜﲐ‌	‌ﭜ‍ + ‍ﲐ‌
uniFB5C(first) + uniFD17(second)	‌ﭜﴗ‌	‌ﭜ‍ + ‍ﴗ‌
uniFB5C(first) + uniFD18(second)	‌ﭜﴘ‌	‌ﭜ‍ + ‍ﴘ‌
uniFB5C(first) + uniFE8A(second)	‌ﭜﺊ‌	‌ﭜ‍ + ‍ﺊ‌
uniFB5C(first) + uniFEF0(second)	‌ﭜﻰ‌	‌ﭜ‍ + ‍ﻰ‌
uniFB5C(first) + uniFEF2(second)	‌ﭜﻲ‌	‌ﭜ‍ + ‍ﻲ‌

(uniFBFE)
uniFBFE(first) + uniFBA9(second)	‌ﯾﮩ‌	‌ﯾ‍ + ‍ﮩ‌
uniFBFE(first) + uniFBAF(second)	‌ﯾﮯ‌	‌ﯾ‍ + ‍ﮯ‌
uniFBFE(first) + uniFBE5(second)	‌ﯾﯥ‌	‌ﯾ‍ + ‍ﯥ‌
uniFBFE(first) + uniFBFD(second)	‌ﯾﯽ‌	‌ﯾ‍ + ‍ﯽ‌
uniFBFE(first) + uniFC10(second)	‌ﯾﰐ‌	‌ﯾ‍ + ‍ﰐ‌
uniFBFE(first) + uniFC90(second)	‌ﯾﲐ‌	‌ﯾ‍ + ‍ﲐ‌
uniFBFE(first) + uniFD17(second)	‌ﯾﴗ‌	‌ﯾ‍ + ‍ﴗ‌
uniFBFE(first) + uniFD18(second)	‌ﯾﴘ‌	‌ﯾ‍ + ‍ﴘ‌
uniFBFE(first) + uniFE8A(second)	‌ﯾﺊ‌	‌ﯾ‍ + ‍ﺊ‌
uniFBFE(first) + uniFEF0(second)	‌ﯾﻰ‌	‌ﯾ‍ + ‍ﻰ‌
uniFBFE(first) + uniFEF2(second)	‌ﯾﻲ‌	‌ﯾ‍ + ‍ﻲ‌

Thanks :)

**Comment by davelab6** [comment]
@graphicore it would be helpful in the testing documents to have a comparison with amiri - and other arabic fonts that are well regarded, like Adobe Arabic that ships with CS, and is available as a web font from https://typekit.com/fonts/adobe-arabic . @Tarobish do you have an adobe CC subscription that you could use for this purpose?

**Comment by Tarobish** [comment]
Great idea, i do @graphicore https://github.com/graphicore

**Comment by graphicore** [comment]
I can add this. What is the preferred mode? Two tables next to each other)? Change the font when hovering a cell or row? Press a key on the keyboard to change to the comparison font (could move the content around bit)? It should be something simple, so that I don't spend too much time with UI development. Right now my approach is very minimalistic.

I'd add a dropdown to select the active comparison font from a list of choices, so we can use Amiri, Adobe Arabic and more.

**Comment by davelab6** [comment]
I can think of 4 comparison modes:

Side by side in cols, for checking vertical aspects

Side by side in rows for checking horizontal aspects

Overlaid with opacity and color for checking all similarities

Copositioned toggling/rotating on keypresses, on a timer, on mouseover, for
checking all differences

Copositioned masking, with a slider, for checking differences

TestMyFont.com has code you can look at for the timed toggle but it's
simple css

**Comment by graphicore** [comment]
@davelab6 I changed the table generating code to a common base. The table can already duplicate the data rows or the data columns. This will get an interface soon.

**Comment by graphicore** [comment]
@Tarobish  check this out (just uni0**\* combinations): 
http://tarobish.github.io/Jomhuria/#tests/collision-above-1
http://tarobish.github.io/Jomhuria/#tests/collision-above-2

I will treat the uniF**\* glyphs extra. And I won't treat the u1EE*\* glyphs.

**Comment by Tarobish** [comment]
Awesome, look perfect :) 

Many thanks

**Comment by graphicore** [comment]
@davelab6 There is some comparison now, in all tables:

screenshot from http://tarobish.github.io/Jomhuria/#tests/collision-above-1

![selection_057](https://cloud.githubusercontent.com/assets/393132/8293807/459ed680-1938-11e5-927b-f04735e52fa6.png)

**Comment by graphicore** [comment]
This is the test for the `uniFxxx` cases which I fixed
http://tarobish.github.io/Jomhuria/#tests/collision-above-1b
