### ISSUE TITLE
Colliding glyph combinations above the baseline

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Jomhuria#12]
like قآ 

uni0642.init
uni06A8.init
uni06A4.init
uni06A6.init
uniFED7
uniFB6C
uniFB70
u1EE32

with combination of

uni0622.fina
uniFE82

**Comment by graphicore** [comment]
@Tarobish checkout http://tarobish.github.io/Jomhuria/#tests/collision-above-3

uniF**\* will get an extra treatment later.

I won't touch u1EE32

**Comment by Tarobish** [comment]
Great :) perfect :)

**Comment by graphicore** [comment]
This is the test for the `uniFxxx` cases, which I fixed
http://tarobish.github.io/Jomhuria/#tests/collision-above-3b

**Comment by Tarobish** [comment]
Great :)
