### ISSUE TITLE
Line height setup

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#16]
This is a follow up of #3 With input from Khaled Hosny

On 06/11/2015 04:40 PM, Khaled Hosny wrote:

> On Thu, Jun 11, 2015 at 04:39:13PM +0200, Lasse Fister wrote:
> 
> > Dave also asked me to set ascender and descender to the global yMin yMax
> > values, But I think the default line-spacing is extreme big now. This is
> > because we have some very extreme characters in the font that push the
> > max-values up; like unicode 06DD ARABIC END OF AYAH.
> 
> Right, that practice does not work well for Arabic. What you should do
> is to set typo and hhea metrics to sensible values that give the line
> spacing you desire, and set win metrics to the max (just ticking the
> offset check mark in FontForge and using 0 as value will do), and just
> ignore apps that still use win metrics for line spacing because they are
> unfixable anyway.
> 
> Regards,
> Khaled

**Comment by graphicore** [comment]
@davelab6 what do you think?

**Comment by davelab6** [comment]
Follow @khaledhosny on this.

**Comment by graphicore** [comment]
now it is:
Ascender: 1840
Descender: -1160

in OS2:

``` xml
    <sTypoAscender value="1840"/>
    <sTypoDescender value="-1160"/>
```

in hhea:

``` xml
    <ascent value="1840"/>
    <descent value="-1160"/>
```

@Tarobish @EbenSorkin Probably as the designers you should decide about the default line-height? I chose something that I think leaves enough room for the dots (it shouldn't be less). However, we can set it to other values.

**Comment by EbenSorkin** [comment]
I agree. Shoot for something that let’s the Arabic breathe enough to be useful and then let users of the Latin reduce linespace if they choose to do that. Kourosh, what vertical metrics values give us that? 

Lasse, I will get you the info needed to begin the contract this evening.

I am finding that the Latin is pretty deeply flawed. The main idea is right in terms of weight and width but I think I probably want to get rid of the slab serifs and replace them with something more old style - or to go Sans. I also want to re-draw the rounds to echo the more sophisticated shapes in the Arabic. I am also very interested in working to echo the density of the Arabic which is very display oriented. At the moment the spacing is too loose to match well.

Anyway - if you would both give me some feedback about these ideas that would be great. I would like to know we are mostly in agreement before I begin. I will of course send you proofs of a limited glyph set early on so we can check that this approach is working together.

-e.

**Comment by graphicore** [comment]
> Lasse, I will get you the info needed to begin the contract this evening.
> …
> I would like to know we are mostly in agreement before I begin. I will of course send you proofs of a limited glyph set early on so we can check that this approach is working together.

Waiting for this.

**Comment by graphicore** [comment]
> Lets try 1800
> As Ascender?

I checked some glyphs with three dots above and below. Their height was my guide. Less would make it possible for these to collide between lines. Wouldn't happen too often, I guess.

**Comment by Tarobish** [comment]
You are absolutely right. lets keep it the way it is.
