### ISSUE TITLE
Arabic/Latin mark/punctuation shapes

### ISSUE THREAD

**Issue by davelab6** [Tarobish/Jomhuria#17]
@Tarobish the Latin punctuation and the Arabic dots (nukta?) look very different, being very round or very square:

![screen shot 2015-06-12 at 5 54 12 pm](https://cloud.githubusercontent.com/assets/261579/8140709/1435b5d2-112c-11e5-91dc-a97916a96b3b.png)

Should one be changed to harmonize or is this a strong design intent?

cc @EbenSorkin

**Comment by Tarobish** [comment]
For the Persian/Arabic the Latin punctuation could be like the one we have (it works better, more harmony with the rest of the characters) but if you think we have to change it, i’ll design something else 
what do you think? cc @EbenSorkin https://github.com/EbenSorkin

**Comment by graphicore** [comment]
We can replace them according to the text-language, if that helps.

**Comment by EbenSorkin** [comment]
Latin punctuation shapes in this case is highly flexible. We can definitely adapt. :-)

On Fri, Jun 12, 2015 at 4:33 PM -0700, "Tarobish" notifications@github.com wrote:

For the Persian/Arabic the Latin punctuation could be like the one we have (it works better, more harmony with the rest of the characters) but if you think we have to change it, i’ll design something else 

what do you think? cc @EbenSorkin https://github.com/EbenSorkin

**Comment by khaledhosny** [comment]
Language/Script-specific glyphs for common punctuation is an option, but note that the selection often fails due to combinations of lack of proper text tagging, bad itemization due to incorrect bidi intervention or both.

**Comment by graphicore** [comment]
What about this, can it be closed?

**Comment by EbenSorkin** [comment]
I was under the impression that Kourosh was Ok with the punctuation now. 

-e.
