### ISSUE TITLE
Position of marks

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Jomhuria#19]
There is Collision with the position of marks in the Arabic when two marks, are coming above and under each other in the same place.

**Comment by graphicore** [comment]
How can I reproduce this?

**Comment by Tarobish** [comment]
I belive some features has broken.
They are in the right position but they don’t works together. 
we need to ask Khaled

**Comment by graphicore** [comment]
Can you show it to me? Or give a string (text) to reproduce it.
I'm thinking we may need a little input box widget to make this kind of work easier...

> we need to ask Khaled

I probably can figure it out, once I can reproduce it myself.

**Comment by graphicore** [comment]
I almost forgot to mention this here. I used the marks.txt to create a pdf and an html test:

https://github.com/Tarobish/Jomhuria/blob/master/generated/documents/marks.pdf
http://tarobish.github.io/Jomhuria/#texts/marks1

It's certainly no good type setting, but I hope its sufficient to identify problems.

@Tarobish tell me, where are the problems?

**Comment by Tarobish** [comment]
I checked the whole pdf, looks great. many thanks, i didn't find any problem :)

**Comment by graphicore** [comment]
So, what's to do here? I did not work this issue (consciously). Can we close this again?

**Comment by graphicore** [comment]
Closing for being inactive, also "looks great. many thanks" implies that this was dealt with.
