### ISSUE TITLE
uni0774.fina_LamAlfFina is missing its indic arabic 3

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#21]
see http://tarobish.github.io/Jomhuria/#tests/kaf-lam-alf-1 the third column from the right side:

![selection_061](https://cloud.githubusercontent.com/assets/393132/8317812/61a2a85c-1a00-11e5-8e21-9f98700f2f16.png)

uni0774.fina should have a small arabic three on the top.

the codepoint is called: _ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE_

![uni0774 fina_lamalffina at 861 from jomhuria-regular_059](https://cloud.githubusercontent.com/assets/393132/8317758/fb20b4de-19ff-11e5-8f2f-d3a4f2b9de04.png)

**Comment by graphicore** [comment]
It's interesting, we have a `aTwo.above` glyph but no `aThree.above`. Do you think we lost it somewhere on our way?

**Comment by Tarobish** [comment]
we have it here, from the bottom the third one

http://tarobish.github.io/Jomhuria/#tests/kaf-lam-alf-1 http://tarobish.github.io/Jomhuria/#tests/kaf-lam-alf-1

**Comment by graphicore** [comment]
You should probably use `uni0663.small`

![selection_062](https://cloud.githubusercontent.com/assets/393132/8318225/3b8c05a2-1a03-11e5-911e-7a9323115a51.png)
`

**Comment by Tarobish** [comment]
Thats right :) i did it

**Comment by graphicore** [comment]
Here we go:

![selection_063](https://cloud.githubusercontent.com/assets/393132/8319109/770a6f76-1a0b-11e5-9d7f-f9dcbe4207e1.png)

**Comment by Tarobish** [comment]
Awesome man :)
