### ISSUE TITLE
Drop Arabic Presentation Forms glyphs

### ISSUE THREAD

**Issue by khaledhosny** [Tarobish/Jomhuria#22]
All the glyphs for characters from `U+FB50` to `U+FEFC` (except `U+FD3E` and `U+FD3F`) that are currently in the font should be removed. They are deprecated legacy characters and are not used in the shaping, so they just bloat the file size. They are included in Amiri for completeness sake.

**Comment by davelab6** [comment]
I recommend waiting for Lasse to merge all these :)
