### ISSUE TITLE
The problem in generating font for Mac

### ISSUE THREAD

**Issue by zoghal** [Tarobish/Jomhuria#23]
Hello
I am researching the problems of Persian fonts in Mac.

I have a problem that so far could not find reason. To illustrate the problem, I created a test on Jomhuria
font.
Please check and review the my branch: https://github.com/font-store/Jomhuria/tree/bug-in-mac

problem: 
I use fontforge(latest release) for generating font. Each font is created when using Final Cut Pro on the problem there: 
![photo_2015-07-31_02-13-27](https://cloud.githubusercontent.com/assets/174688/9007204/57fbc858-37a4-11e5-9ab7-4d971371c6a8.jpg)

but existing other font without problem, for example [X yekan](https://github.com/font-store/Jomhuria/tree/bug-in-mac/good-font)

![photo_2015-07-31_02-13-05](https://cloud.githubusercontent.com/assets/174688/9007246/c54e3238-37a4-11e5-8101-2a324bf090a2.jpg)
I know the problem is in the generating aat features . But do not know how to must correct converting opentype features to AAT .
@davelab6, @graphicore  can help me, thanks.

**Comment by graphicore** [comment]
Have you also tested this file: https://github.com/Tarobish/Jomhuria/blob/master/generated/Jomhuria-Regular.ttf ?

**Comment by zoghal** [comment]
@graphicore Yes, I tried, but the font does not appear in the list of fonts
![photo_2015-07-31_20-11-55](https://cloud.githubusercontent.com/assets/174688/9012871/7c7980b6-37cd-11e5-8375-6d5f7e6daa2d.jpg)

**Comment by graphicore** [comment]
So what did you change in your version to make it appear in the menu?

**Comment by zoghal** [comment]
I've applied a lot of changes.
em size set 2048.
os/2 version set 1
when generate i select and check apple in sfnt options
and ....

**Comment by davelab6** [comment]
I think you need to write new AAT table data

On Friday, 31 July 2015, Saleh Souzanchi notifications@github.com wrote:

> Hello
> I am researching the problems of Persian fonts in Mac.
> 
> I have a problem that so far could not find reason. To illustrate the
> problem, I created a test on Jomhuria
> font.
> Please check and review the my branch:
> https://github.com/font-store/Jomhuria/tree/bug-in-mac
> 
> problem:
> I use fontforge(latest release) for generating font. Each font is created
> when using Final Cut Pro on the problem there:
> [image: photo_2015-07-31_02-13-27]
> https://cloud.githubusercontent.com/assets/174688/9007204/57fbc858-37a4-11e5-9ab7-4d971371c6a8.jpg
> 
> but existing other font without problem, for example X yekan
> https://github.com/font-store/Jomhuria/tree/bug-in-mac/good-font
> 
> [image: photo_2015-07-31_02-13-05]
> https://cloud.githubusercontent.com/assets/174688/9007246/c54e3238-37a4-11e5-8101-2a324bf090a2.jpg
> I know the problem is in the generating aat features . But do not know how
> to must correct converting opentype features to AAT .
> @davelab6 https://github.com/davelab6, @graphicore
> https://github.com/graphicore can help me, thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tarobish/Jomhuria/issues/23.

## 

Cheers
Dave

**Comment by khaledhosny** [comment]
Is Final Cut Pro a Carbon application? If so then OpenType fonts will not work and I’d close this as WONTFIX myself as Carbon is deprecated technology and writing AAT support is not trivial and there is no reliable way to automatically convert OpenType layout to AAT.

**Comment by graphicore** [comment]
@khaledhosny interesting, thanks! I was going to ask next how Amiri behaves in this case ;-)

**Comment by davelab6** [comment]
Yeah i think it is carbon.

**Comment by graphicore** [comment]
I looks like current Final Cut Pro is Cocoa [as stated on wikipedia](https://en.wikipedia.org/wiki/Final_Cut_Pro) but there it has a different look ![screenshot](https://upload.wikimedia.org/wikipedia/en/a/a5/Final_Cut_Pro_X.jpg)

@zoghal what's your version of Final Cut Pro?

**Comment by zoghal** [comment]
@graphicore  my frind test with 7.0.3 and 10 of Final Cut Pro.
ok, Unfortunately I'm using Windows and Linux.
I have to say someone else will do it.
Thank
