### ISSUE TITLE
The placement of U+0620 ring is incorrect

### ISSUE THREAD

**Issue by khaledhosny** [Tarobish/Jomhuria#26]
The ring here should be detached from the base i.e. like a dot, unlike other letters with a ring below.

**Comment by graphicore** [comment]
@khaledhosny does this look allright:

http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6IiYjeDA2MjA7XG48c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MjA7PC9zcGFuPiIsImJpZGkiOiJydGwiLCJsYW5nIjoiYXIifQ==

![selection_006](https://cloud.githubusercontent.com/assets/393132/10004879/5a73d4ac-60b4-11e5-821d-a951695af364.png)

(Amiri on the left)

**Comment by khaledhosny** [comment]
Yes, looks fine, but make sure all forms of the character does so as well.

**Comment by graphicore** [comment]
I see.

**Comment by graphicore** [comment]
Here is the complete case

http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6IiYjeDA2MjA7ICAmI3gwNjIwOyYjODIwNTsgICAmIzgyMDU7JiN4MDYyMDsmIzgyMDU7ICAmIzgyMDU7JiN4MDYyMDsgXG5cbjxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYyMDsgICYjeDA2MjA7JiM4MjA1OyAgICYjODIwNTsmI3gwNjIwOyYjODIwNTsgICYjODIwNTsmI3gwNjIwOyA8L3NwYW4+IiwiYmlkaSI6InJ0bCIsImxhbmciOiJhciJ9

![selection_007](https://cloud.githubusercontent.com/assets/393132/10005294/ae5814fa-60b6-11e5-8905-07c7597cb27d.png)

**Comment by khaledhosny** [comment]
Just compare it to ي, the ring should be positioned similar to the dots. You might also need to check any alternate glyphs for those.

http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6IiYjeDA2MjA7ICAmI3gwNjIwOyYjODIwNTsgICAmIzgyMDU7JiN4MDYyMDsmIzgyMDU7ICAmIzgyMDU7JiN4MDYyMDsgXG5cbiYjeDA2NEE7ICAmI3gwNjRBOyYjODIwNTsgICAmIzgyMDU7JiN4MDY0QTsmIzgyMDU7ICAmIzgyMDU7JiN4MDY0QTsgIiwiYmlkaSI6InJ0bCIsImxhbmciOiJhciJ9

**Comment by graphicore** [comment]
I was just about to push this:

![selection_008](https://cloud.githubusercontent.com/assets/393132/10006006/d4cfba26-60ba-11e5-9153-6b3ecae66ab3.png)

I also fixed the alternative forms.

**Comment by graphicore** [comment]
right, a push to gh-pages closes this issue ... reopened

**Comment by khaledhosny** [comment]
Looks good.

**Comment by graphicore** [comment]
great, thanks
