### ISSUE TITLE
Arabic subtending marks are broken

### ISSUE THREAD

**Issue by khaledhosny** [Tarobish/Jomhuria#27]
- [x] The glyphs have -ve side bearing which will cause them to overlap with neighbouring glyphs. The side bearings should be +ve (or zero at least).
- [x] The positioning rules of the digits needs to be adjusted as the existing one are copied from amiri and they are specific to Amiri’s glyph widths.

**Comment by graphicore** [comment]
Here is an initial case:

http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6InxKb21odXJpYXw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPkFtaXJpPC9zcGFuPnxcbnwtLXwtLXxcbnwg2aHZotmj2aR8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj7Zodmi2aPZpDwvc3Bhbj58XG58JiN4MDYwMDvZodmi2aPZpOKArOKArHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA72aHZotmj2aTigKzigKw8L3NwYW4+fFxufCYjeDA2MDE72aHZotmj2aTigKzigKx8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAxO9mh2aLZo9mk4oCs4oCsPC9zcGFuPnxcbnwmI3gwNjAyO9mh2aJ8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAyO9mh2aI8L3NwYW4+fFxufCYjeDA2MDM72aHZotmjfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMzvZodmi2aPigKzigKzigKzigKw8L3NwYW4+fFxufCYjeDA2ZGQ72aHZotmj4oCs4oCsfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDZkZDvZodmi2aM8L3NwYW4+fFxuXG5cblxuXG5cblxuXG5cblxuXG5cblxuIiwiYmlkaSI6InJ0bCIsImxhbmciOiJhciJ9

![selection_009](https://cloud.githubusercontent.com/assets/393132/10007375/ed7a5ef0-60c4-11e5-8582-fbcb563ace6b.png)

I'll do my best, because I think this is hard to do for @Tarobish; given the handwritten nature of the mentioned  positioning rules.

**Comment by Tarobish** [comment]
:) Thanks

**Comment by graphicore** [comment]
I reopen to wait for the OK of @khaledhosny 

[that's a pretty long test document](http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6InxKb21odXJpYXw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPkFtaXJpPC9zcGFuPnxcbnwtLXwtLXxcbnwqKnVuaTA2MDAqKnwgKyAxIHxcbnwmI3gwNjAwO9mjfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMDvZozwvc3Bhbj58XG58JiN4MDYwMDvZpHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA72aQ8L3NwYW4+fFxufCYjeDA2MDA72aB8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAwO9mgPC9zcGFuPnxcbnwmI3gwNjAwOzd8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAwOzc8L3NwYW4+fFxufCoqdW5pMDYwMCoqfCArIDIgfFxufCYjeDA2MDA72aLZo3w8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA72aLZozwvc3Bhbj58XG58JiN4MDYwMDvZpNmlfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMDvZpNmlPC9zcGFuPnxcbnwmI3gwNjAwOzbZoHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA7NtmgPC9zcGFuPnxcbnwmI3gwNjAwOzk3fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMDs5Nzwvc3Bhbj58XG58Kip1bmkwNjAwLjMqKnwgKyAzIHxcbnwmI3gwNjAwO9mh2aLZo3w8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA72aHZotmjPC9zcGFuPnxcbnwmI3gwNjAwO9mk2abZpXw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA72aTZptmlPC9zcGFuPnxcbnwmI3gwNjAwOzbZoDR8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAwOzbZoDQ8L3NwYW4+fFxufCYjeDA2MDA7OTQ3fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMDs5NDc8L3NwYW4+fFxufCoqdW5pMDYwMC40Kip8ICsgNCB8XG58JiN4MDYwMDvZodmi2afZo3w8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA72aHZotmn2aM8L3NwYW4+fFxufCYjeDA2MDA72aTZqdmm2aV8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAwO9mk2anZptmlPC9zcGFuPnxcbnwmI3gwNjAwO9mo2aA2NHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDA72ajZoDY0PC9zcGFuPnxcbnwmI3gwNjAwOzkyNDd8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAwOzkyNDc8L3NwYW4+fFxufCoqdW5pMDYwMSoqfCArIDEgfFxufCYjeDA2MDE72aF8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAxO9mhPC9zcGFuPnxcbnwmI3gwNjAxO9mgfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTvZoDwvc3Bhbj58XG58JiN4MDYwMTvZqHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDE72ag8L3NwYW4+fFxufCYjeDA2MDE7NHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDE7NDwvc3Bhbj58XG58JiN4MDYwMTs3fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTs3PC9zcGFuPnxcbnwqKnVuaTA2MDEqKnwgKyAyIHxcbnwmI3gwNjAxO9mo2aF8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAxO9mo2aE8L3NwYW4+fFxufCYjeDA2MDE72aXZoHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDE72aXZoDwvc3Bhbj58XG58JiN4MDYwMTvZp9mofDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTvZp9moPC9zcGFuPnxcbnwmI3gwNjAxOzg0fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTs4NDwvc3Bhbj58XG58JiN4MDYwMTs0N3w8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDE7NDc8L3NwYW4+fFxufCoqdW5pMDYwMSoqfCArIDMgfFxufCYjeDA2MDE72anZqNmhfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTvZqdmo2aE8L3NwYW4+fFxufCYjeDA2MDE72aHZpdmgfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTvZodml2aA8L3NwYW4+fFxufCYjeDA2MDE72aXZp9mofDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTvZpdmn2ag8L3NwYW4+fFxufCYjeDA2MDE7OTg0fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTs5ODQ8L3NwYW4+fFxufCYjeDA2MDE7MjQ3fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTsyNDc8L3NwYW4+fFxufCoqdW5pMDYwMSoqfCArIDQgfFxufCYjeDA2MDE72aHZqdmo2aF8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAxO9mh2anZqNmhPC9zcGFuPnxcbnwmI3gwNjAxO9mi2aDZodmlfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTvZotmg2aHZpTwvc3Bhbj58XG58JiN4MDYwMTvZo9ml2afZqHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDE72aPZpdmn2ag8L3NwYW4+fFxufCYjeDA2MDE7MTk4NHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDE7MTk4NDwvc3Bhbj58XG58JiN4MDYwMTs5MjQ3fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMTs5MjQ3PC9zcGFuPnxcbnwqKnVuaTA2MDIqKnwgKyAxIHxcbnwmI3gwNjAyO9mmfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMjvZpjwvc3Bhbj58XG58JiN4MDYwMjvZqHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDI72ag8L3NwYW4+fFxufCYjeDA2MDI72aB8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAyO9mgPC9zcGFuPnxcbnwmI3gwNjAyOzl8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAyOzk8L3NwYW4+fFxufCoqdW5pMDYwMioqfCArIDIgfFxufCYjeDA2MDI72aHZonw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDI72aHZojwvc3Bhbj58XG58JiN4MDYwMjvZpNmpfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMjvZpNmpPC9zcGFuPnxcbnwmI3gwNjAyO9mn2aN8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAyO9mn2aM8L3NwYW4+fFxufCYjeDA2MDI72abZpXw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDI72abZpTwvc3Bhbj58XG58JiN4MDYwMjvZqNmgfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMjvZqNmgPC9zcGFuPnxcbnwmI3gwNjAyOzc5fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMjs3OTwvc3Bhbj58XG58Kip1bmkwNjAzKip8ICsgMSB8XG58JiN4MDYwMzvZqXw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDM72ak8L3NwYW4+fFxufCYjeDA2MDM72aV8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAzO9mlPC9zcGFuPnxcbnwmI3gwNjAzO9mofDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMzvZqDwvc3Bhbj58XG58JiN4MDYwMzs0fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMzs0PC9zcGFuPnxcbnwmI3gwNjAzOzd8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAzOzc8L3NwYW4+fFxufCoqdW5pMDYwMyoqfCArIDIgfFxufCYjeDA2MDM72anZqHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDM72anZqDwvc3Bhbj58XG58JiN4MDYwMzvZodmlfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMzvZodmlPC9zcGFuPnxcbnwmI3gwNjAzO9mn2ah8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAzO9mn2ag8L3NwYW4+fFxufCYjeDA2MDM7OTR8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNjAzOzk0PC9zcGFuPnxcbnwmI3gwNjAzOzI3fDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDYwMzsyNzwvc3Bhbj58XG58Kip1bmkwNjAzLjMqKnwgKyAzIHxcbnwmI3gwNjAzO9mp2ajZoXw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDM72anZqNmhPC9zcGFuPnxcbnwmI3gwNjAzO9mh2aXZoHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDM72aHZpdmgPC9zcGFuPnxcbnwmI3gwNjAzO9ml2afZqHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDM72aXZp9moPC9zcGFuPnxcbnwmI3gwNjAzOzk4NHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDM7OTg0PC9zcGFuPnxcbnwmI3gwNjAzOzI0N3w8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2MDM7MjQ3PC9zcGFuPnxcbnwqKnVuaTA2ZGQqKnwgKyAxIHxcbnwmI3gwNmRkO9mh4oCs4oCsfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDZkZDvZoTwvc3Bhbj58XG58JiN4MDZkZDsyfDxzcGFuIHN0eWxlPVwiZm9udC1mYW1pbHk6IEFtaXJpXCI+JiN4MDZkZDsyPC9zcGFuPnxcbnwqKnVuaTA2ZGQqKnwgKyAyIHxcbnwmI3gwNmRkO9ml2ad8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNmRkO9ml2ac8L3NwYW4+fFxufCYjeDA2ZGQ7OTF8PHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTogQW1pcmlcIj4mI3gwNmRkOzkxPC9zcGFuPnxcbnwqKnVuaTA2ZGQqKnwgKyAzIHxcbnwmI3gwNmRkO9ml2aLZo+KArOKArHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2ZGQ72aXZotmjPC9zcGFuPnxcbnwmI3gwNmRkOzU2N+KArOKArHw8c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OiBBbWlyaVwiPiYjeDA2ZGQ7NTY3PC9zcGFuPnxcbiIsImJpZGkiOiJydGwiLCJsYW5nIjoiYXIifQ==)

**Comment by khaledhosny** [comment]
Looks good to me, great job!

**Comment by graphicore** [comment]
Cool, thanks!
