### ISSUE TITLE
Remove unaccessible glyphs

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#28]
After the last session of removing unaccessible glyphs the font had some changes to it. So, now it is worth checking if there are further glyphs that became inaccessible.

**Comment by graphicore** [comment]
Just checked, found nothing.

**Comment by khaledhosny** [comment]
You can also use something like  `pyftsubset jomhuria-regular.ttf --unicodes='*' --layout-features='*' --name-IDs='*'` and it should drop any unused glyph, unreferenced lookup, redundant name platforms and so on.
