### ISSUE TITLE
Broken marks

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#33]
Another screenshot from @Tarobish 

![screen shot 2015-09-10 at 8 41 54 pm](https://cloud.githubusercontent.com/assets/393132/9894966/3aa9d696-5c2a-11e5-9c48-7c1b26703659.png)

That's from https://github.com/Tarobish/Jomhuria/blob/master/generated/documents/marks.pdf 3rd page first line.

It's also reproducible here:

http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6IiAjINis2Y7YsdmN2ZEg2LHZjdmRICIsImJpZGkiOiJydGwiLCJsYW5nIjoiYXIifQ==
![selection_073](https://cloud.githubusercontent.com/assets/393132/9895035/00b79dd2-5c2b-11e5-9c58-af33fd1a375b.png)

**Comment by graphicore** [comment]
Here is a hint from Kourosh where the vowel should actually be:

![screen shot 2015-09-10 at 8 47 14 pm](https://cloud.githubusercontent.com/assets/393132/9895064/6fbb36f8-5c2b-11e5-8470-8ee4b08bd0bc.png)

**Comment by graphicore** [comment]
I think this is a broken or not happening Mark to Mark positioning.

**Comment by graphicore** [comment]
Here is another issue with missing marks. This was introduced by the new latin design:

http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6ItqA2KfZnOKAjCDagNil2ZzigIwg2oDdtNmc4oCMINqA3bPZnOKAjCDagNij2ZzigIwg2oDYotmc4oCMINqA2bXZnOKAjCDagNmy2ZzigIwg2oDZs9mc4oCMINqA2bHZnOKAjCBcblxu2oDYp8yl4oCMINqA2KXMpeKAjCDagN20zKXigIwg2oDds8yl4oCMINqA2KPMpeKAjCDagNiizKXigIwg2oDZtcyl4oCMINqA2bLMpeKAjCDagNmzzKXigIwg2oDZscylXG4iLCJiaWRpIjoicnRsIiwibGFuZyI6ImFyIn0=

![selection_075](https://cloud.githubusercontent.com/assets/393132/9959040/4da8323c-5e10-11e5-816d-d4ef060fe7ae.png)

Can also be witnessed in http://tarobish.github.io/Jomhuria/#tests/collision-below-2

The broken glyph in this case is: uni0325

**Comment by graphicore** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/393132/9995168/f84b90f4-6080-11e5-94b0-9996d51a148e.png)

![selection_002](https://cloud.githubusercontent.com/assets/393132/9995207/2d7af68e-6081-11e5-98eb-bd180af665a7.png)

![selection_003](https://cloud.githubusercontent.com/assets/393132/9995225/4d36b6fc-6081-11e5-80c1-365661857cc2.png)

**Comment by Tarobish** [comment]
Nice :)
