### ISSUE TITLE
Drop the Arabic documentation

### ISSUE THREAD

**Issue by khaledhosny** [Tarobish/Jomhuria#34]
The `documentation-arabic.tex` file is full of references to Amiri, so unless you plan to update it (which requires someone who knows Arabic, no I do not volunteer, I couldn’t even finish it for Amiri), it would be better to drop it entirely.

**Comment by graphicore** [comment]
Yeah, it was handy to test the font in the beginning, but I agree that it is pretty confusing as a "documentation file"

**Comment by graphicore** [comment]
I think I'll drop it after #27 is fixed. What I want to do next.
