### ISSUE TITLE
Add links from text page to repo and back

### ISSUE THREAD

**Issue by davelab6** [Tarobish/Jomhuria#35]
- [x] In the testing page - http://tarobish.github.io/Jomhuria/ - add a link in the sidebar to https://github.com/Tarobish/Jomhuria/
- [x] On the repo page - https://github.com/Tarobish/Jomhuria - add a link at the top to the testing page

**Comment by graphicore** [comment]
This counters a bit my strategy to just run `git checkout gh-pages && git rebase master && git push`

**Comment by davelab6** [comment]
What is the purpose of that?

**Comment by graphicore** [comment]
It has maybe the same effect as making gh-pages the main branch of the repository, as mentioned by you in #36 

> https://github.com/Tarobish/Jomhuria/tree/master can be removed? It is identical to gh-pages and you can set gh-pages to be the default branch

It updates gh-pages to the state of master and then pushes it.

With different versions of README.md it would probably have conflicts. (maybe not if done in the right order). The starting page in gh-pages is using README.md directly, not a copy of its contents.

The best solution is maybe to add a link to the testing page in README.md and to add a link to the repository somewhere in the testing page where it is independent of the README.md

**Comment by davelab6** [comment]
This is different. 2nd thing is not about a link in README. Its about a link in the github page metadata, which only @Tarobish can edit, maybe, unless you are a 'owner' class collaborator. 

1st thing is adding `<li><a href="https://github.com/Tarobish/Jomhuria/">Github Project</a></li>`

**Comment by graphicore** [comment]
Right, and they would still appear at different URLs.

**Comment by graphicore** [comment]
@Tarobish it's at the top of the repository, only you can do it. Like here:

![selection_076](https://cloud.githubusercontent.com/assets/393132/10118009/1c3ee44a-646c-11e5-8ef1-09fd083e6cf9.png)

I also added https://github.com/Tarobish/Jomhuria#preview
