### ISSUE TITLE
Close dead branches

### ISSUE THREAD

**Issue by davelab6** [Tarobish/Jomhuria#36]
- [x] https://github.com/Tarobish/Jomhuria/tree/diet can be removed?
- [x] https://github.com/Tarobish/Jomhuria/tree/initial can be removed?
- [x] https://github.com/Tarobish/Jomhuria/tree/master can be removed? It is identical to gh-pages and you can set gh-pages to be the default branch in https://github.com/Tarobish/Jomhuria/settings and then remove master. You can see their differences at https://github.com/Tarobish/Jomhuria/compare/master%40%7B1day%7D...master

**Comment by graphicore** [comment]
`initial` and `diet` are gone.

The 3rd: not sure about this, I like it when master is the default branch, it's a convention. I'd prefer to make master the branch displayed at http://tarobish.github.io/Jomhuria but I think that's impossible.

**Comment by davelab6** [comment]
Yes, it is impossible. 

Its a convention but it doesn't really matter. `git clone URL` will always take the default branch; 'master' label for the default branch is just a convention, nothing more :)

**Comment by graphicore** [comment]
ok. @Tarobish can you go to the https://github.com/Tarobish/Jomhuria/settings/branches and set 
**Default branch** to `gh-pages` (it's `master` now)

**Comment by Tarobish** [comment]
Done! :)
