### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by davelab6** [Tarobish/Jomhuria#39]
- [x] OS/2 table `<achVendID value="    "/>` should be `<achVendID value="GRCR"/>` for Graphicore, or whatever. 
- [x] NAME table ID 5 is `Version 000.001` but should be `Version 1.000` (and increment to 1.001 and 1.002 and so on each time the binary is updated.)
- [x]  NAME table ID 9 is `Kourosh Beigpour, Lasse Fister` but should be more like `Arabic design by Kourosh Beigpour, Latin design by Eben Sorkin, engineering by Lasse Fister and Khaled Hosney`
- [x] NAME table ID 1 is `Copyright 2015 Korosh Beigpour (www.k-b-studio.com|tarobish@gmail.com). Copyright 2015 Lasse Fister (lasse@graphicore.de). Copyright 2015 Sorkin Type Co (www.sorkintype.com). Copyright 2010-2015 Khaled Hosny (khaledhosny@eglug.org).` but should be the same as my PR https://github.com/Tarobish/Jomhuria/pull/38/files
- [x] Vertical metrics are not right. 

```
$ fontbakery-fix-vertical-metrics.py *tf
WARNING: Jomhuria-Regular.ttf has NOT even heights
Parameter              Jomhuria-Regular.ttf    
ymax                   3083                    
hhea.ascent            1840                    
OS/2.sTypoAscender     1840                    
OS/2.usWinAscent       3083                    
ymin                   -1575                   
hhea.descent           -1160                   
OS/2.sTypoDescender    -1160                   
OS/2.usWinDescent      1575                    
hhea.lineGap           0                       
OS/2.sTypoLineGap      0                       
hhea total             3000                    
typo total             3000                    
win total              4658                    
UPM:Heights            3000:4658               
UPM:Heights %          155 %                   

Low Glyphs
Jomhuria-Regular.ttf: uni08FA uni08F2 uni08F9 uni08E9 uni08E6 uni08EF uni08EE uni064D uni065F uni0656 uni0650 uni06DD uni06E3 uni06ED uni06EA uni061A smallv.below.inverted smallv.below uni06D0.fina uni0650.small2

$ fontbakery-fix-vertical-metrics.py --autofix *tf
$ fontbakery-fix-vertical-metrics.py *tf.fix;
Parameter              Jomhuria-Regular.ttf.fix    
ymax                   3083                        
hhea.ascent            3083                        
OS/2.sTypoAscender     3083                        
OS/2.usWinAscent       3083                        
ymin                   -1575                       
hhea.descent           -1575                       
OS/2.sTypoDescender    -1575                       
OS/2.usWinDescent      1575                        
hhea.lineGap           0                           
OS/2.sTypoLineGap      0                           
hhea total             4658                        
typo total             4658                        
win total              4658                        
UPM:Heights            3000:4658                   
UPM:Heights %          155 %                       
$
```

**Comment by graphicore** [comment]
I think the vertical metrics were set on purpose like this.

#3 #16 https://github.com/Tarobish/Jomhuria/issues/16#issuecomment-111624565

https://github.com/Tarobish/Jomhuria/commit/33f1b5b2cc76283363e0141b210c685b85607d2c

**Comment by davelab6** [comment]
From 3, 

> I can also get some glyphs with the highest and lowest y values pretty fast and easy with python, if that is interesting.

The fontbakery-fix-vmetrics.py script does this already. 

@khaledhosny wrote in 16,

> What you should do is to set typo and hhea metrics to sensible values that give the line spacing you desire, and set win metrics to the max (just ticking the offset check mark in FontForge and using 0 as value will do), and just ignore apps that still use win metrics for line spacing because they are unfixable anyway.

How have you tested vertical metrics like this in Amiri? The vertical metrics for Amiri that I onboarded to google/fonts are not modified and are as follows:

```
$ fontbakery-fix-vertical-metrics.py *tf
WARNING: Inconsistent OS/2.usWinDescent OS/2.usWinAscent

WARNING: Amiri-Bold.ttf has NOT even heights
WARNING: Amiri-BoldSlanted.ttf has NOT even heights
WARNING: Amiri-Regular.ttf has NOT even heights
WARNING: Amiri-Slanted.ttf has NOT even heights
Parameter              Amiri-Bold.ttf    Amiri-BoldSlanted.ttf    Amiri-Regular.ttf    Amiri-Slanted.ttf    
ymax                   3734              3734                     3717                 3717                 
hhea.ascent            2300              2300                     2300                 2300                 
OS/2.sTypoAscender     2300              2300                     2300                 2300                 
OS/2.usWinAscent       3834              3834                     3817                 3817                 
ymin                   -1863             -1863                    -1843                -1843                
hhea.descent           -1300             -1300                    -1300                -1300                
OS/2.sTypoDescender    -1300             -1300                    -1300                -1300                
OS/2.usWinDescent      1963              1963                     1943                 1943                 
hhea.lineGap           0                 0                        0                    0                    
OS/2.sTypoLineGap      0                 0                        0                    0                    
hhea total             3600              3600                     3600                 3600                 
typo total             3600              3600                     3600                 3600                 
win total              5797              5797                     5760                 5760                 
UPM:Heights            2048:5597         2048:5597                2048:5560            2048:5560            
UPM:Heights %          273 %             273 %                    271 %                271 %                

Low Glyphs
Amiri-Bold.ttf: glyph04723 glyph02026 glyph02020 glyph04701 glyph02627 glyph02628 uni064D glyph03919 glyph04789 glyph04899 glyph05591 glyph04679 glyph04613 glyph04635 glyph00845 glyph05496 glyph05009 glyph04987 glyph03289 glyph02019 glyph01542 glyph01541 glyph01548 glyph04528 glyph02196 glyph01563 glyph04657 uni0656 glyph01998 glyph01997 glyph05542 glyph04943 glyph03634 glyph04965 glyph03205 glyph05364 glyph05362 glyph05588 glyph05587 glyph00987 uni08F2 glyph04877 glyph03164 glyph03212 glyph04855 glyph04486 glyph01747 glyph04833 glyph00814 glyph04921 glyph03206 uni06ED uni06EA glyph03860 glyph04767 glyph00857 glyph01662 glyph01661 glyph01668 glyph04745 glyph04219 glyph01416 glyph03296 glyph03290
Amiri-BoldSlanted.ttf: glyph02000 glyph04725 glyph04530 glyph02021 glyph02022 glyph02028 glyph04703 glyph04791 glyph02629 glyph01550 uni064D glyph03214 glyph04488 glyph05590 glyph05593 glyph04659 glyph04967 glyph01418 glyph04615 glyph04637 glyph05589 glyph00847 glyph05498 glyph01670 glyph04989 glyph04901 glyph01543 glyph01544 glyph03921 glyph02630 glyph02198 glyph01565 uni0656 glyph01999 glyph05544 glyph03208 glyph04923 glyph03207 glyph04945 glyph03636 glyph05366 glyph05364 glyph00989 uni08F2 glyph04879 glyph03166 glyph01749 glyph04835 glyph00816 uni06ED uni06EA glyph03862 glyph05011 glyph04769 glyph00859 glyph04681 glyph01663 glyph01664 glyph04857 glyph04747 glyph04221 glyph03298 glyph03291 glyph03292
Amiri-Regular.ttf: glyph03356 glyph03350 glyph00958 u1EE87 u1EE82 u1EE8C glyph05640 uni064D glyph04911 glyph04889 glyph05686 glyph01685 glyph01686 glyph04977 glyph05506 glyph05109 glyph02164 glyph02163 glyph04672 glyph02141 glyph04845 glyph04823 glyph05065 glyph03434 glyph04630 glyph04801 glyph05043 glyph03308 glyph05021 glyph04779 glyph03433 glyph01806 glyph01805 glyph02340 glyph03349 glyph04004 u1EE97 glyph01560 uni0656 glyph05087 glyph01692 glyph04867 glyph05153 glyph04363 glyph00989 glyph02170 uni08F2 glyph02771 glyph02772 glyph04757 glyph01707 glyph05131 glyph04933 glyph05735 glyph05731 glyph05732 glyph04063 uni06ED uni06EA glyph03440 glyph01812 glyph04999
Amiri-Slanted.ttf: glyph04725 glyph04530 glyph02021 glyph02022 glyph02028 glyph04703 glyph04791 glyph02629 glyph01550 uni064D glyph03214 glyph04488 glyph05590 glyph05593 glyph04659 glyph04967 glyph01418 glyph04615 glyph04637 glyph05589 glyph00847 glyph05498 glyph01670 glyph04989 glyph04901 glyph01543 glyph01544 glyph03921 glyph02630 glyph02198 glyph01565 uni0656 glyph01999 glyph05544 glyph03208 glyph04923 glyph03207 glyph04945 glyph05364 uni08F2 glyph04879 glyph03166 glyph04835 glyph00816 uni06ED uni06EA glyph03862 glyph05011 glyph04769 glyph04681 glyph01663 glyph01664 glyph04857 glyph04747 glyph04221 glyph03298 glyph03291 glyph03292

WARNING: Inconsistent OS/2.usWinDescent: Amiri-Bold.ttf, Amiri-BoldSlanted.ttf
WARNING: Inconsistent OS/2.usWinAscent: Amiri-Bold.ttf, Amiri-BoldSlanted.ttf
```

**Comment by khaledhosny** [comment]
I don’t see anything wrong here, Win metrics are for clipping, so they are 100 + max on each side, and they need not be consistent across the family for that very reason (if applications are using them for line height, that is their problem we can’t really do anything to help it here).

The other metrics are choosing to give reasonable default line height, though it might not suite all kinds of text that can be set with Amiri (for a fully vocalised text like Quran, I’d definitely use much bigger leading). People who don’t like the default should override it, and that is my general advice especially on the web where it is the only way to get consistent results across platforms.

No idea what low glyphs mean exactly, but those are behind a stylistic set and it is reasonable not to punish the default line height just for them, not to mention that in Arabic there are lots of vertical space so even with a bit tight leading there is high chance that such glyphs will not overlap.

**Comment by khaledhosny** [comment]
The extra 100 in Win metrics was to account for possible combining marks, but I probably meant it to be 1000 as 100 is just too low; I have single diacritics that are 800+ and they can even stack. But I never encountered an app that enforces the clipping, though it seem to be a common thing on Windows.

**Comment by graphicore** [comment]
about this:

> NAME table ID 1 is Copyright 2015 Korosh Beigpour (www.k-b-studio.com|tarobish@gmail.com). Copyright 2015 Lasse Fister (lasse@graphicore.de). Copyright 2015 Sorkin Type Co (www.sorkintype.com). Copyright 2010-2015 Khaled Hosny (khaledhosny@eglug.org). but should be the same as my PR https://github.com/Tarobish/Jomhuria/pull/38/files

@Tarobish said he'd strongly prefer "Kourosh" over "Mehdi"
and I remember that @davelab6 suggested using "KB-Studio" or something like that, if KB-Studio is a registered company. Tell me what you want to have guys.

**Comment by graphicore** [comment]
The `NAME table ID 1, Copyright` is now the same as in https://github.com/Tarobish/Jomhuria/blob/gh-pages/OFL.txt but the question if that is the version that everybody agrees upon is still open.

> Vertical metrics are not right.

Still waiting for a definite answer.

**Comment by davelab6** [comment]
> @Tarobish said he'd strongly prefer "Kourosh" over "Mehdi"

Okay, I think its good to make that change and then we're done

> Vertical metrics are not right.

Let's follow khaled's advice on this for now

**Comment by graphicore** [comment]
It's now

> Copyright 2015 Kourosh Beigpour (www.k-b-studio.com|tarobish@gmail.com). Copyright 2015 Lasse Fister (lasse@graphicore.de). Copyright 2015 Sorkin Type Co (www.sorkintype.com). Copyright 2010-2015 Khaled Hosny (khaledhosny@eglug.org).

Is that correct, and should I send a new `Jomhuria-1.000.zip` for verification?

**Comment by graphicore** [comment]
Here, I found that old conversation I was referring to:

> > > dave:
> > > If you have a company name, you can use it because it is a 'legal name' 
> > 
> > korosh:
> > Yes! its KB-Studio 
> 
> dave:
> Yeah use that

That implies rather to go with:

> Copyright 2015 KB-Studio (www.k-b-studio.com|tarobish@gmail.com). Copyright 2015 Lasse Fister (lasse@graphicore.de). Copyright 2015 Sorkin Type Co (www.sorkintype.com). Copyright 2010-2015 Khaled Hosny (khaledhosny@eglug.org).

**Comment by davelab6** [comment]
Yes, that's good

**Comment by graphicore** [comment]
Sorry, which one is good: `KB-Studio` or `Kourosh Beigpour`

**Comment by davelab6** [comment]
Studio

**Comment by Tarobish** [comment]
Hi,
Yes KB - Studio it's a registered company 

KB STUDIO

**Comment by Tarobish** [comment]
Great!

KB STUDIO

**Comment by davelab6** [comment]
@graphicore K
