### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by davelab6** [Tarobish/Jomhuria#4]
Currently the README has only 

> A persian/arabic and latin fat display font

@Tarobish please write a few paragraphs describing the project, your inspirations/sources for the design, etc

**Comment by graphicore** [comment]
@davelab6  Here is a draft. Kourosh sent it to me, I reworded it a bit. Do you think it's appropriate?

> Jomhuria [Republic] is a bold Persian/Arabic and Latin display typeface suitable in title and headline design.
> A stencil of “Shablon”—showing just limited character set just for the Persian language without any marks, vowels or Latin glyphs—was the spark of inspiration. Shablon was designed 30 years ago in Iran. When re-designing it (I|Kourosh) incorporated contemporary techniques, aesthetics and of course some personal taste. Taking its origin in the spirit of Shablon, Jomhuria evolved to a new typeface of its own.
> 
> The font comprises an original Latin design tailored to go well with the aesthetics of the Persian/Arabic style.
> 
> Being made for big sizes means details matter. For the first time in Persian/Arabic typography the positions of the dots remain unchanged to where they are located in hand-written calligraphy; this is a most important factor of beauty in the design of this script and it improves the readability.
> Designed by Kourosh Beigpour, engineered by Lasse Fister. “Amiri” by Khaled Hosny was the blueprint project for Jomhuria.
