### ISSUE TITLE
Categorising Arabic fonts

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Jomhuria#40]
Hi All,
Here is a problem, normally in the softwares like (illustrator, indesign or Microsoft word) Persian/Arabic fonts are divided by a tiny line to separate them from latin, Chinese, etc... but Jomhuria, after installing it goes under Latin category (Amiri also facing a same problem)
Does anyone has an idea?

**Comment by davelab6** [comment]
cc @khaledhosny 

I guessed maybe the codepage info was not set, but it was:

![screen shot 2015-09-26 at 12 20 03](https://cloud.githubusercontent.com/assets/261579/10118553/ee9aa808-6448-11e5-985d-c2b615f59078.png)

**Comment by khaledhosny** [comment]
No idea really, anyone knows what Adobe bases its classification on?

**Comment by davelab6** [comment]
@readroberts is there an afdko method for setting this?

**Comment by graphicore** [comment]
ping

**Comment by Oldouze** [comment]
Hi there,
Wasn't sure where else I could comment but just wanted to let you know that I downloaded and used this font and I really like it! It's beautiful and versatile. Quite excited to have this as part of my font collection. Well done!

**Comment by solargaria** [comment]
I trying it in Adobe Indesign. for make books in Jawi language (Old malay with Arabic scripts), It's working good... thank you

**Comment by davelab6** [comment]
It seems that adobe software uses an unpublished heuristic to determine this, and only setting the codepage support to Arabic may work.

**Comment by khaledhosny** [comment]
Setting it to Arabic only?

**Comment by graphicore** [comment]
@Tarobish is Mirza and/or Katibeh working in this context?

I could compare some of the tables. `OS/2`, `name` what could be relevant here?

**Comment by Tarobish** [comment]
Yes, both are working perfect. i think "Glyphs App" did something by default to categorized them

**Comment by davelab6** [comment]
This was discussed on the glyphs forum.
https://forum.glyphsapp.com/t/place-font-on-hebrew-font-list/3856/10

**Comment by davelab6** [comment]
@graphicore any luck with this?

**Comment by graphicore** [comment]
To speed the needle in the haystack search up a bit.
@Tarobish for Mirza and Katibeh, under which names are the fonts reported in your InDesign menu for Persian/Arabic fonts?

**Comment by Tarobish** [comment]
The whole Arabic, Persian fonts are in the same place included Mirza and Katibeh 

KB STUDIO

**Comment by graphicore** [comment]
But not in Arabic script? It says in Latin "Mirza" and "Katibeh"?

**Comment by davelab6** [comment]
Screenshot + unicode text that you see would be ideal

**Comment by Tarobish** [comment]
No, in the Arabic script, we just have this problem with jomhuria

![screen shot 2016-02-26 at 6 11 52 pm](https://cloud.githubusercontent.com/assets/8403973/13370134/8f5f3bd0-dcb4-11e5-8336-7b608ebe483e.png)

**Comment by graphicore** [comment]
@Tarobish can you please download and test this file: https://github.com/Tarobish/Jomhuria/raw/issue_40/generated/Jomhuria-Regular.ttf

**Comment by Tarobish** [comment]
Still in the latin category but there is another problem, the position of anchor above the baseline (in the extension part) its broken :(
![screen shot 2016-03-01 at 10 51 07 am](https://cloud.githubusercontent.com/assets/8403973/13438138/87ff772a-df9c-11e5-84b5-dc8c3de75e95.png)

**Comment by Tarobish** [comment]
Its broken here too

![screen shot 2016-03-01 at 10 59 29 am](https://cloud.githubusercontent.com/assets/8403973/13438177/bda4329e-df9c-11e5-92d8-22f3f77f4924.png)

**Comment by graphicore** [comment]
That's very off-topic. Please make an issue if it is so in the versions in gh-pages as well.
The font at the link I posted is to work on the category problem.

**Comment by Tarobish** [comment]
Sorry :) Just deleted them all
No still it doesn't

**Comment by graphicore** [comment]
NP, just make a new issue, describe what you did and the software and post a live testing page.

**Comment by Tarobish** [comment]
Sure :)

**Comment by graphicore** [comment]
@Tarobish: please download and test again: file: https://github.com/Tarobish/Jomhuria/raw/issue_40/generated/Jomhuria-Regular.ttf
(Make sure you restart InDesign after installing the font.)

**Comment by Tarobish** [comment]
Still it doesn't

**Comment by graphicore** [comment]
This is a mystery. In the [issue_40](https://github.com/Tarobish/Jomhuria/tree/issue_40) I did:

``` py
>>> font['OS/2'].ulCodePageRange1 = 64
>>> font['OS/2'].ulCodePageRange2 = 0
```

and

``` py
>>> font['OS/2'].ulUnicodeRange1 = 8193
>>> font['OS/2'].ulUnicodeRange2 = 0
>>> font['OS/2'].ulUnicodeRange3 = 8
>>> font['OS/2'].ulUnicodeRaneg4 = 0
```

So that these values match exactly the values of Katibeh, which is reported to work. I don't have an idea which other value could be responsible for this.
I coud try to use the Katibeh `name` and `OS/2` tables completely and then, and if it works, go towards the Jomhuria tables until it breaks? Any Idea anyone? Could any other table be responisble? (`name` looks just fine for the purpose and is just like Katibeh, it has the same fields, so I rule that out)

@Tarobish are you sure your InDesign updated the font you used? Do you use your system-wide font installation or the InDesign folder?

https://helpx.adobe.com/indesign/using/using-fonts.html#installing_fonts

> You can make fonts available in InDesign by copying the font files into the `Fonts` folder inside the InDesign application folder on your hard drive. However, fonts in this Fonts folder are available only to InDesign. 

I believe I've heard that the InDesign folder was better to test fonts and I want to rule out it being a caching issue or such.

**Comment by Tarobish** [comment]
Yes I did but let me try one more time
I'll delete everything, restart the whole system and re-install again

KB STUDIO

**Comment by Tarobish** [comment]
just updated the indesign and we are fine :)

**Comment by graphicore** [comment]
Really? Which font did work? Is there a difference between the one in the `issue_40` branch and the version in `gh_pages`?

**Comment by Tarobish** [comment]
Yes :) the one in the issue #40 the second one that you sent me
this one 
 https://github.com/Tarobish/Jomhuria/raw/issue_40/generated/Jomhuria-Regular.ttf

**Comment by graphicore** [comment]
Yeah, give it a trial! But I think the version in between (the first I posted today) is the one that made the difference. So, please can you test this one as well: https://github.com/Tarobish/Jomhuria/raw/94ae05b2f5f987ea91c25c32bfc292dbfff58359/generated/Jomhuria-Regular.ttf (use the link here, it's from the history of issue_40)

**Comment by Tarobish** [comment]
Sure :)

KB STUDIO

**Comment by Tarobish** [comment]
yeah, its fine :)

**Comment by graphicore** [comment]
> yeah, its fine :)

Which one?

**Comment by Tarobish** [comment]
The link in you last comment

Yeah, give it a trial! But I think the version in between (the first I posted today) is the one that made the difference. So, please can you test this one as well: https://github.com/Tarobish/Jomhuria/raw/94ae05b2f5f987ea91c25c32bfc292dbfff58359/generated/Jomhuria-Regular.ttf (use the link here, it's from the history of issue_40)

**Comment by graphicore** [comment]
OK, so that refers to this change:

```
>>> font['OS/2'].ulCodePageRange1 = 64
>>> font['OS/2'].ulCodePageRange2 = 0
```

Which essentially says the only codepage that "[is considered functional](https://www.microsoft.com/typography/otspec/os2.htm#cpr)" is Arabic.

Before we had bit's set for a lot of Latin based codepages as well. Seems that Adobe's algorithm just prefers Latin. I'll update the main build script to set these Flags.

**Comment by graphicore** [comment]
I updated the font in gh-pages. Feel free to test it one last time.

**Comment by davelab6** [comment]
Thought it would be codepages! Cool!
