### ISSUE TITLE
Anchors its broken, in "Hah fina"

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Jomhuria#42]
http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6Itit2ZAg2K3ZjSIsImJpZGkiOiJydGwiLCJsYW5nIjoiYXIifQ==

![bda4329e-df9c-11e5-92d8-22f3f77f4924](https://cloud.githubusercontent.com/assets/8403973/13439617/2f477054-dfa3-11e5-9105-5d85c89c647f.png)

**Comment by graphicore** [comment]
the live testing link above gives me this:

![selection_085](https://cloud.githubusercontent.com/assets/393132/13447568/dca92ade-e01c-11e5-877f-99d8c371ba39.png)

Looks like missing anchors.

**Comment by Tarobish** [comment]
Just added, please check it out

**Comment by graphicore** [comment]
No update received. Note that you must switch your local branch to `gh-pages`. The graphical Github client that you have should be able to do so. I don't know how to do it with sparkle share though; but, once switched Sparkleshare should work again. (You want to do this for Mirza and Katibeh as well, BTW)

**Comment by Tarobish** [comment]
Check it now plz

**Comment by Tarobish** [comment]
I think i did it with the Jomhuria but to be honest no idea about the rest :)

**Comment by graphicore** [comment]
Nah, you pushed to master, but we don't use master anymore.

Here are recent changes made by you:
https://github.com/Tarobish/Jomhuria/tree/master

Here they should be (`gh-pages`) https://github.com/Tarobish/Jomhuria

@davelab6 troubles for Kourosh to switch branches may be a good reason to keep the `master`/`gh-pages` duplication (referring to #36)

**Comment by Tarobish** [comment]
I did it :) right?

**Comment by graphicore** [comment]
Hehe, yeah, that's ok, too. You'll have trouble to stay in sync so, if you don't rebase your `master` branch from time to time ;-)

**Comment by Tarobish** [comment]
I see :)

**Comment by graphicore** [comment]
Oh, in your merged PR #44 Is see messages like `Merge remote-tracking branch 'origin/gh-pages'`

That means something on you computer is syncing with gh-pages …

**Comment by Tarobish** [comment]
Is that bad or...?

**Comment by graphicore** [comment]
Rather good.

**Comment by graphicore** [comment]
This looks fine now, on the live testing page:

![selection_087](https://cloud.githubusercontent.com/assets/393132/13449644/e344bffa-e02d-11e5-8f93-085f641267cf.png)

Maybe you want to check in InDesign

**Comment by Tarobish** [comment]
Great! works here too
