### ISSUE TITLE
We lost some characters:  "uni06F4.urd.medium", "uni06F4.urd.small" and "uni06F6.urd.medium”

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#5]
> they are umbers in urdu we need them all but i didn’t find the glyphs to add the characters

**Comment by khaledhosny** [comment]
Do you have tests for Arabic subtending marks (where these glyphs are used)? I can imaging that you will need to adjust the (needlessly complex, but OpenType…) kerning features used to position those, unless your digits and marks has the exact same advance widths as in Amiri.

**Comment by khaledhosny** [comment]
There is a table in page 3 of the documentation-arabic.pdf, and the position is off for most of them.

**Comment by graphicore** [comment]
Thanks for the reminder. I think I will wait until the Latin font is ready. Then we can care for all of the numbers in one go. There is still Amiri-kerning left in https://github.com/Tarobish/Jomhuria/blob/master/sources/enclosing.fea

**Comment by graphicore** [comment]
Hmm, for this case we wouldn't have to wait for latin at all, right?

**Comment by khaledhosny** [comment]
In Amiri the Arabic and Latin digits had the same width, so the code handled them all similarly, so I think you only need to wait for Latin just to confirm if this still the case or not.
