### ISSUE TITLE
it seems the features of the glyphs are broken

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#7]
@Tarobish 

> please check the font
> i changed the colors of some characters in light blush and green
> it seem the feature of the glyphs has been broken
> when these glyphs are coming together (each one of the light blue in connection with each of the green one ) they have a different sort of connection
> the engine can read the cods but is something is broken
> like this

![screen shot 2015-06-05 at 4 44 19 pm](https://cloud.githubusercontent.com/assets/393132/8019344/06fa260a-0c4a-11e5-9426-4fa4a856c2d4.png)

**Comment by zoghal** [comment]
in naskh and Titr style of arabic/persian  this is true: 
demo1 : http://share.pho.to/9SG7m/cr/original
demo 2: http://share.pho.to/9SG8y/ty/original

**Comment by davelab6** [comment]
@zoghal what are those 2 fonts? :)

**Comment by zoghal** [comment]
@davelab6 These two new Persian fonts. Diba and Ordibehesht.

**Comment by davelab6** [comment]
That you designed? :)

**Comment by zoghal** [comment]
No, I'm not a designer, I am a developer.
I'm working on a startup or project research that will help Iranian designers to design standard fonts for farsi.

**Comment by davelab6** [comment]
Ok :) Where are these fonts from?

**Comment by Tarobish** [comment]
I know the designer 
Diba it has been design by damoon khanjanzadeh
And ordibehesht it is an old Persian typeset has been developed recently

**Comment by zoghal** [comment]
Diba :
designer : Damon khan janzade 

Ordibehesht : 
orginal designer :unknown designer (main source is letraset)
this front has The two designers claim fonts and each chose a different name.
ordibehest and todeh :d fallow this [link](http://www.roozrang.com/%D8%A8%D8%B1%D8%AE%D9%88%D8%B1%D8%AF%DB%8C-%D9%85%D8%B9%D8%A7%D8%B5%D8%B1-%D8%A7%D8%B2-%D8%AA%D8%A7%DB%8C%D9%BE-%D8%B3%D9%86%DA%AF%DB%8C%D9%86-%D8%B9%D9%84%D9%8A%D8%B1%D8%B6%D8%A7-%D8%B9%D8%B3%D9%83/)

i am supporting and help to ordibehesht for publishing with ofl license (https://github.com/font-store/Font-Ordibehesht)

**Comment by graphicore** [comment]
@Tarobish I think the first one (on the right side, with aKaf.medi_KafLam plus the LamAlfFina) is broken because the left side bearing is to far on the left side. See the image below.

The glyph should rather start where the base-line connects. Or you do it with kerning, but either way, I think that's your task.

![akaf medi_kaflam at 197 from jomhuria-regular_053](https://cloud.githubusercontent.com/assets/393132/8290310/8693fdac-1922-11e5-91e8-2be7d41aa3fe.png)

I'm checking the other combination now.

**Comment by Tarobish** [comment]
No, it has to be like this. the point is, it will be connected with the right side of the next character. please see below. or you think it has to be done by kerning? please let me know
![screen shot 2015-06-22 at 12 15 21 pm](https://cloud.githubusercontent.com/assets/8403973/8290680/773b10be-18d9-11e5-87f6-b815c6340254.png)
![screen shot 2015-06-22 at 12 15 35 pm](https://cloud.githubusercontent.com/assets/8403973/8290682/7a7d9058-18d9-11e5-9e5a-d4257437274d.png)
![screen shot 2015-06-22 at 12 15 59 pm](https://cloud.githubusercontent.com/assets/8403973/8290686/7cfd2104-18d9-11e5-8141-ad6bd541525a.png)
![screen shot 2015-06-22 at 12 16 20 pm](https://cloud.githubusercontent.com/assets/8403973/8290689/80910f9c-18d9-11e5-8958-a64d2913ebb9.png)
![screen shot 2015-06-22 at 12 16 25 pm](https://cloud.githubusercontent.com/assets/8403973/8290691/82f65116-18d9-11e5-980c-09c7d0bc77a8.png)
![screen shot 2015-06-22 at 12 19 49 pm](https://cloud.githubusercontent.com/assets/8403973/8290693/85963d8c-18d9-11e5-8844-2c830b43f4f7.png)

**Comment by graphicore** [comment]
Please stay at the first example. I think we have a different issue with the second one.

Yes I think it has to be done with kerning. But not with the kern feature, but with the glyph being shorter itself.

**Comment by graphicore** [comment]
Like this:

![akaf medi_kaflam at 197 from jomhuria-regular-_054](https://cloud.githubusercontent.com/assets/393132/8291061/5751402c-1927-11e5-9b11-531c49fcfc6a.png)

**Comment by graphicore** [comment]
On the other hand. You show ligatures `uniFCEB` `uniFC80` etc. Do you think Amiri used these? The feature must have gone lost in Toronto then.

**Comment by graphicore** [comment]
The original character, with the sidebearing you gave it, how is it supposed to connect anyways? I can't imagine that there is a single working combination this way.

**Comment by Tarobish** [comment]
yes, This is from Amiri, i believe we kept this feature. otherwise we lost in Toronto.

**Comment by Tarobish** [comment]
It's simple. the red lines are R&L bearing from the "Kaf" and the blue one belong to the next character "lam"
easily they will be connected. please let me know if I'm wrong :)
![773b10be-18d9-11e5-87f6-b815c6340254](https://cloud.githubusercontent.com/assets/8403973/8291572/45b4d0ba-18df-11e5-9e31-50f95c3f49b7.png)

**Comment by graphicore** [comment]
If these shapes meet each other in text, the red and blue lines in the middle would be aligned. Therefore the gap happens.

**Comment by graphicore** [comment]
In Amiri, the baseline ends with the left side-bearing:

![akaf medi_kaflam at 65802 from amiri-bold_055](https://cloud.githubusercontent.com/assets/393132/8291967/14088518-192d-11e5-8768-8c00b5dcf921.png)

**Comment by graphicore** [comment]
This is what we are doing here:
![Kerning](http://typedeck.com/wp-content/uploads/2011/09/20090513TT_fg01.jpg)

The solid block under the glyph shapes, that's the side bearings. Think about your red/blue line example in these terms.

**Comment by Tarobish** [comment]
I think, the baseline ends with the left side-bearing because of the Khaled's design. if we do that our ligature its going to be like this :( I'm right? or I'm confused :(
![screen shot 2015-06-22 at 1 29 44 pm](https://cloud.githubusercontent.com/assets/8403973/8292223/484e9c08-18e3-11e5-9528-f37ef6656fa0.png)

**Comment by graphicore** [comment]
The thing is that we don't actually show the ligature in the text. The ligature is in this legacy unicode code block, that is not really used anymore. What we do instead is showing `uni0643.med_KafLam` and then `uni0644.medi_KafĹam`. But for that, the glyph `uni0643.med_KafLam` is broken.
Now, when you repair the glyph, your Ligature breaks, because the positioning is done relative to the left side of the glyph (which is zero in the coordinate system).

**Comment by graphicore** [comment]
I just fixed the other issue with the other combination. Now we have the same problem there:

![selection_056](https://cloud.githubusercontent.com/assets/393132/8292866/1d6e1ab4-1932-11e5-91ef-ca77ac59c3ed.png)

**Comment by graphicore** [comment]
I updated the pdfs and gh-pages, you can observe there.

**Comment by Tarobish** [comment]
Now I got :)
I'll fix it :) I have to redesign these characters 
Thanks

**Comment by graphicore** [comment]
I made two test tables:

http://tarobish.github.io/Jomhuria/#tests/kaf-lam-alf-1
http://tarobish.github.io/Jomhuria/#tests/kaf-lam-alf-2

**Comment by khaledhosny** [comment]
If you want the kaf to touch the lam, then you should decrease the left side bearing, otherwise you can always have a contextual form for the kaf when followed by lam.

**Comment by Tarobish** [comment]
Thanks, got it. i have to redesign the “Kaf"

**Comment by graphicore** [comment]
@Tarobish Why don't do just as I did [here](https://github.com/Tarobish/Jomhuria/issues/7#issuecomment-114232972) and then repair the ligature glyphs. What do you plan to redesign?

**Comment by Tarobish** [comment]
thats what i want to do (the way you did it) but i have to work on the top side of the “Kaf” this way its going to be a bit short.

**Comment by graphicore** [comment]
OK

**Comment by Tarobish** [comment]
I just committed, please check it and let me know

**Comment by graphicore** [comment]
Looking good :-) check the pdfs and this stuff:

http://tarobish.github.io/Jomhuria/#tests/kaf-lam-alf-1
http://tarobish.github.io/Jomhuria/#tests/kaf-lam-alf-2

**Comment by Tarobish** [comment]
Perfect :)
![screen shot 2015-06-23 at 2 34 58 pm](https://cloud.githubusercontent.com/assets/8403973/8317846/30ff0042-19b5-11e5-84ff-2fa0022432fe.png)
