### ISSUE TITLE
Clean up kerning features

### ISSUE THREAD

**Issue by graphicore** [Tarobish/Jomhuria#8]
@Tarobish 

> Pleas also check the kerning features 
> i believe it has to be something there from Amiri
> many Thanks :)

**Comment by graphicore** [comment]
Indeed there is kerning from Amiri:

https://github.com/Tarobish/Jomhuria/blob/master/sources/kerning.fea

I'm going to remove this.

**Comment by graphicore** [comment]
Ok, the upcoming push will have a commit that empties `kerning fea`. However, we should check if we need to get some of the kerning back in again.

Below, especially the last part  after `// proportional digits` seems like it could be useful to me.
It is for kerning of Arabic-Indic proportional digits. I think I have to set up a testcase for these.

@Tarobish are there any other blocks below that look to you like we need it (probably with different values)

This is What I removed:

``` fea

@Dal_1 = [@aDal.fina @aDal.isol];
@1st_2 = [@RaaWaw @AlefHamzaBelow];
@1st_4 = [@aHeh.isol @aHeh.fina];

// final alef with no hamza above
@Alf_1 = [uni0627.fina_LamAlfFina uni0625.fina_LamAlfFina];
@Alf_2 = [@aAlf.fina @aAlf.fina_KafAlf
          @aAlf.fina_LamAlfFina @aAlf.fina_LamAlfIsol];

@Kaf_3 = [@aKaf.init @aKaf.init_KafLam @aGaf.isol];

@Raa_1 = [@RaaWaw @aDal.fina @aDal.isol];

lookup YaaBari3Kern {
  pos @aAyn.init <0 0 440 0>;
  pos @aFaa.init <0 0 710 0>;
  pos @aHeh.init <0 0 400 0>;
  pos @aLam.init <0 0 955 0>;
  pos @aMem.init <0 0 520 0>;
  pos @aSen.init <0 0 150 0>;
  pos @aTaa.init <0 0 150 0>;
  pos uni06BE.init <0 0 400 0>;
} YaaBari3Kern;

feature kern {
  lookupflag IgnoreMarks;
  pos @RaaWaw' <-300 0 -300 0> [@Kaf_3];

  pos @Dal_1'  <-400 0 -400 0> [@Kaf_3];

  // increase advance width for first glyph in 3-letter Baree Yaa ligatures
  pos [@aAyn.init @aFaa.init @aHeh.init @aLam.init
       @aMem.init @aSen.init @aTaa.init uni06BE.init]' lookup YaaBari3Kern
       @aBaa.medi;
} kern;

// we don't want to ignore marks here
feature kern {
  pos @Alf_1' <-250 0 -250 0> @Kaf_3;

  // raa/waw/dal followed by isolated dagger alef followed by madda needs some
  // space to avoid fatha/madda clash
  pos @Raa_1' < 200 0  200 0> uni064E uni0670.isol [uni0653 uni06E4];

  pos [uni0621]' < 200 0  200 0> uni064E uni0670.isol;
} kern;

feature kern {
  lookupflag IgnoreMarks;
  pos @RaaWaw' <80 0 80 0> @aYaa.init;
  pos @RaaWaw' <120 0 120 0> uni061B; // Arabic semicolon
} kern;

feature kern {
  lookupflag IgnoreMarks;
  // kern heh isol/final followed by kaf, does not happen in Arabic but can be
  // seen in Kurdish or Persian using ZWNJ between them.
  pos @1st_4 uni200C [@Kaf_3]' -500;
  // Uniscribe replace ZWNJ with space
  pos @1st_4 space   [@Kaf_3]' -500;
  // some applications might just remove it
  pos @1st_4         [@Kaf_3]' -500;
} kern;

feature kern {
  lookupflag IgnoreMarks;
    pos period.ara' <-300 0 -300 0> [quotedblleft quoteleft];
    pos period' -150 [quotedblright quoteright];
} kern;


// proportional digits
feature kern {
  pos uni0661.prop uni0662.prop -100;
  pos uni0661.prop uni0663.prop -100;
  pos uni0661.prop uni0666.prop -200;
  pos uni0661.prop uni0669.prop -100;

  pos uni0662.prop uni0667.prop  100;
  pos uni0662.prop uni0668.prop  -50;

  pos uni0663.prop uni0667.prop  100;

  pos uni0664.prop uni0661.prop  -50;
  pos uni0664.prop uni0668.prop   50;

  pos uni0666.prop uni0661.prop  -50;

  pos uni0667.prop uni0661.prop  -50;
  pos uni0667.prop uni0668.prop  -50;

  pos uni0668.prop uni0661.prop -100;
  pos uni0668.prop uni0662.prop -100;
  pos uni0668.prop uni0663.prop -100;
  pos uni0668.prop uni0666.prop -100;
  pos uni0668.prop uni0667.prop -100;

  pos uni0669.prop uni0668.prop   50;
  pos uni0669.prop uni0660.prop   50;

  pos uni0660.prop uni0667.prop   50;
  pos uni0660.prop uni0668.prop   50;
} kern;

```

**Comment by graphicore** [comment]
> keep it if you think its going to be useful. 

I will make a document for the proportional Arabic figures. The rest I will prune.

**Comment by graphicore** [comment]
Looks to me like all our figures are proportional. The standard figures which are proportional did not receive kerning either. So I close this, because the initial indication of this issue is not given.

http://tarobish.github.io/Jomhuria/#live?eyJ2YWx1ZSI6IiYjeDA2NjA7JiN4MDY2MTsmI3gwNjYyOyYjeDA2NjM7JiN4MDY2NDsmI3gwNjY1OyYjeDA2NjY7JiN4MDY2NzsmI3gwNjY4OyYjeDA2Njk7XG5cbjAxMjM0NTY3ODlcblxuPHNwYW4gc3R5bGU9XCJcbiAgZm9udC12YXJpYW50LW51bWVyaWM6IHByb3BvcnRpb25hbC1udW1zO1xuICAtbW96LWZvbnQtZmVhdHVyZS1zZXR0aW5nczogJ3BudW0nO1xuICAtbXMtZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XG4gIC13ZWJraXQtZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XG4gIGZvbnQtZmVhdHVyZS1zZXR0aW5nczogJ3BudW0nO1wiPlxuJiN4MDY2MDsmI3gwNjYxOyYjeDA2NjI7JiN4MDY2MzsmI3gwNjY0OyYjeDA2NjU7JiN4MDY2NjsmI3gwNjY3OyYjeDA2Njg7JiN4MDY2OTtcbjwvc3Bhbj5cblxuXG48c3BhbiBzdHlsZT1cIlxuICBmb250LXZhcmlhbnQtbnVtZXJpYzogcHJvcG9ydGlvbmFsLW51bXM7XG4gIC1tb3otZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XG4gIC1tcy1mb250LWZlYXR1cmUtc2V0dGluZ3M6ICdwbnVtJztcbiAgLXdlYmtpdC1mb250LWZlYXR1cmUtc2V0dGluZ3M6ICdwbnVtJztcbiAgZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XCI+XG4wMTIzNDU2Nzg5XG48L3NwYW4+XG5cbi0tLVxuXG48c3BhbiBzdHlsZT1cImZvbnQtZmFtaWx5OkFtaXJpXCI+JiN4MDY2MDsmI3gwNjYxOyYjeDA2NjI7JiN4MDY2MzsmI3gwNjY0OyYjeDA2NjU7JiN4MDY2NjsmI3gwNjY3OyYjeDA2Njg7JiN4MDY2OTs8L3NwYW4+XG5cblxuPHNwYW4gc3R5bGU9XCJmb250LWZhbWlseTpBbWlyaVwiPjAxMjM0NTY3ODk8L3NwYW4+XG5cbjxzcGFuIHN0eWxlPVwiXG5mb250LWZhbWlseTpBbWlyaTtcbiAgZm9udC12YXJpYW50LW51bWVyaWM6IHByb3BvcnRpb25hbC1udW1zO1xuICAtbW96LWZvbnQtZmVhdHVyZS1zZXR0aW5nczogJ3BudW0nO1xuICAtbXMtZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XG4gIC13ZWJraXQtZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XG4gIGZvbnQtZmVhdHVyZS1zZXR0aW5nczogJ3BudW0nO1wiPlxuJiN4MDY2MDsmI3gwNjYxOyYjeDA2NjI7JiN4MDY2MzsmI3gwNjY0OyYjeDA2NjU7JiN4MDY2NjsmI3gwNjY3OyYjeDA2Njg7JiN4MDY2OTtcbjwvc3Bhbj5cblxuPHNwYW4gc3R5bGU9XCJcbmZvbnQtZmFtaWx5OkFtaXJpO1xuICBmb250LXZhcmlhbnQtbnVtZXJpYzogcHJvcG9ydGlvbmFsLW51bXM7XG4gIC1tb3otZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XG4gIC1tcy1mb250LWZlYXR1cmUtc2V0dGluZ3M6ICdwbnVtJztcbiAgLXdlYmtpdC1mb250LWZlYXR1cmUtc2V0dGluZ3M6ICdwbnVtJztcbiAgZm9udC1mZWF0dXJlLXNldHRpbmdzOiAncG51bSc7XCI+XG4wMTIzNDU2Nzg5XG48L3NwYW4+XG4iLCJiaWRpIjoibHRyIiwibGFuZyI6ImFyIn0=

**Comment by davelab6** [comment]
You used the local host url again. I suggest using a big colored toolbar at
the top with a big button, share link, that makes a goo.gl or whatever link
to the canonical host domain.

**Comment by graphicore** [comment]
I fixed the link already. I think the github email to you went out before.

**Comment by davelab6** [comment]
Yeah they go out instant I think
