### ISSUE TITLE
features left from Amiri

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Jomhuria#9]
features left from Amiri (I'v seen this some others palaces in our text samples. in Arabic uni062A.inti has a vertical dots, but it seem it is feature lefts from Amiri
![screen shot 2015-06-06 at 10 48 28 am](https://cloud.githubusercontent.com/assets/8403973/8020781/d640f0ac-0c3a-11e5-80d4-8698e74cdf7b.png)

**Comment by graphicore** [comment]
I can't find the same word anymore. The positions changed a lot because of the changed line-height. However, there was a lot of instances in the document.

I removed the rule at the bottom of this post.
Note the

```
   script arab;
   language ARA;
```

Part, this means this should not be active for Farsi. Should we keep it and try if the words render correct when we set the right language? Or don't we need it at all?

```
feature calt {
   lookupflag IgnoreMarks;
   script arab;
   language ARA;

   // Replace teh init following teh/theh medi by a teh init with two vertical
   // dots.
   sub uni062A.init'
       [uni062A.medi uni062B.medi]
   by uni067A.init;

   sub uni062A.init_High'
       [uni062A.medi_High uni062B.medi_High]
    by uni067A.init_High;
} calt;
```

**Comment by graphicore** [comment]
> I didn’t find any problem in Farsi
> But is the "vertical dots" thing something useful in Arabic?

**Comment by graphicore** [comment]
Ok, great. I'm closing this.

**Comment by khaledhosny** [comment]
For the record, this feature in Amiri is used to avoid colliding the dots of these glyph as the dots are wider than the base glyphs here, but as this is not an issue with your font it can go. Using vertical dots to solve this kind of collision is rather common in traditional Arabic styles (where it is likely to happen), but even modern, simplified designs with always-vertical dots are not unseen.

**Comment by graphicore** [comment]
Yeah, I thought so. We have solved it differently though.
